# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/AI/project/project.srcs/sources_1/ip/ila_1/ila.xci
# IP: The module: 'ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/AI/project/project.gen/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/AI/project/project.gen/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/AI/project/project.gen/sources_1/ip/ila_1/ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/AI/project/project.srcs/sources_1/ip/ila_1/ila.xci
# IP: The module: 'ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/AI/project/project.gen/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/AI/project/project.gen/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: f:/AI/project/project.gen/sources_1/ip/ila_1/ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
